version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: calendso
    #volumes: 
    #  - /custom/mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
  # ports:
  #    - 8080:8080
  
  calendso:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: calendso
    ports:
      - "3000:3000"
    depends_on:
      - db
